### ISSUE TITLE
Backlight doesn't turn on

### ISSUE THREAD

**Issue by Ro-Den** [antony-jr/postmarketos-asus-z00l#3]
Hello!

Do you still maintain the device?

Everything is working fine except ):

1.  Back light refuses to turn on at all. I've managed to turn it on once by
`$ echo 50 > /sys/class/backlight/1a98000.dsi.0/brightness`
`$ echo 250 > /sys/class/backlight/1a98000.dsi.0/brightness`
but it's not sustainable.

2. No Internet after connecting to Wi-Fi - maybe an AP issue, needs further investigation...

Unfortunately, my device is a little bit broken with the Power Button completely ripped off. But I don't think it has something to do with the issues ):

Also, fastboot commands don't work in the lk2nd mode. Should they?

**Comment by antony-jr** [comment]
@Ro-Den my device is currently has broken display, so I'm not maintaining it actively right now. Backlight issue seems to be something related to build? Wifi will work but the signal range is very bad. So You have to be close to the AP. I highly suggest using mobile data instead of Wifi since wifi is not sustainable.

**Comment by Ro-Den** [comment]
The issue was solved in kernel 6.6.0
